# =============================================================================
# MathKernel - Exact polynomial algebra: Gröbner bases, multivariate division, resultants,
# Copyright (c) 2026 Maarten Boone
# SPDX-License-Identifier: MIT
# =============================================================================
"""Exact polynomial algebra: Gröbner bases, multivariate division, resultants,
discriminants, factorization, and ideal membership.

Everything here is exact over the coefficient domains SymPy supports (ZZ, QQ,
algebraic extensions); there is deliberately no numeric path — a numeric
Gröbner basis is a different (approximate) theory. All functions operate on
SymPy expressions/polys; the kernel facade handles MathIR conversion.

Batch operations go through the persistent process pool because SymPy is
pure Python and GIL-bound.
"""
from __future__ import annotations

import sympy as sp

from .engines import SymPyEngine
from .parallel import process_map, resolve_workers
from .parser import parse_math

_ORDERS = {"lex", "grlex", "grevlex", "ilex", "igrlex", "igrevlex"}
MAX_POLYS = 64
MAX_VARIABLES = 16


def _restricted_expr(text: str, variables: list[sp.Symbol] | None = None) -> sp.Basic:
    """Parse a polynomial-side string through MathKernel's restricted MathIR."""
    variables = list(variables or [])
    env = {symbol.name: symbol for symbol in variables}
    return SymPyEngine().to_sympy(parse_math(str(text)), env)


def _check_sizes(polys: list, variables: list) -> None:
    if len(polys) > MAX_POLYS:
        raise ValueError(f"at most {MAX_POLYS} polynomials per call")
    if len(variables) > MAX_VARIABLES:
        raise ValueError(f"at most {MAX_VARIABLES} variables per call")
    if not variables:
        raise ValueError("at least one variable is required")


def _order(order: str):
    if order not in _ORDERS:
        raise ValueError(f"unsupported monomial order: {order}; choose from {sorted(_ORDERS)}")
    return order


def groebner_basis(polys: list, variables: list, order: str = "lex") -> list:
    """Reduced Gröbner basis of the ideal generated by `polys`. Exact."""
    _check_sizes(polys, variables)
    basis = sp.groebner(polys, *variables, order=_order(order))
    return [sp.expand(g.as_expr()) for g in basis.polys]


def poly_divide(dividend, divisors: list, variables: list, order: str = "lex"):
    """Multivariate division: returns (quotients, remainder) with
    dividend = sum(q_i * d_i) + remainder. Exact."""
    _check_sizes([dividend, *divisors], variables)
    quotients, remainder = sp.reduced(dividend, divisors, *variables, order=_order(order))
    return [sp.expand(q) for q in quotients], sp.expand(remainder)


def ideal_membership(poly, generators: list, variables: list, order: str = "lex"):
    """Exact ideal membership test: poly ∈ <generators> iff its remainder on
    division by a Gröbner basis is zero. Returns (is_member, remainder)."""
    _check_sizes([poly, *generators], variables)
    basis = sp.groebner(generators, *variables, order=_order(order))
    _, remainder = sp.reduced(poly, [g.as_expr() for g in basis.polys], *variables, order=_order(order))
    remainder = sp.expand(remainder)
    return remainder == 0, remainder


def resultant_poly(p, q, variable):
    """Exact resultant of two polynomials with respect to `variable`."""
    return sp.resultant(p, q, variable)


def discriminant_poly(p, variable):
    """Exact discriminant of a univariate polynomial."""
    return sp.discriminant(p, variable)


def factor_poly(p, variables: list | None = None, extension: str | None = None):
    """Exact factorization over ZZ/QQ, optionally over an algebraic extension
    (e.g. extension='sqrt(2)'). Returns (constant, [(factor, multiplicity)])."""
    variables = variables or sorted(p.free_symbols, key=str)
    _check_sizes([p], list(variables))
    ext = _restricted_expr(extension, list(variables)) if extension else None
    result = sp.factor_list(p, *variables, extension=ext)
    constant, factors = result
    return constant, [(sp.expand(f), int(m)) for f, m in factors]


# -- batch (process pool; jobs are picklable string payloads) -----------------

def _groebner_job(job: dict) -> dict:
    try:
        variables = [sp.Symbol(v) for v in job["variables"]]
        polys = [_restricted_expr(s, variables) for s in job["polys"]]
        basis = groebner_basis(polys, variables, job.get("order", "lex"))
        return {"ok": True, "basis": [str(g) for g in basis]}
    except Exception as exc:  # per-job isolation inside a batch
        return {"ok": False, "error": f"{type(exc).__name__}: {exc}"}


def groebner_batch(jobs: list[dict], workers: int | None = None) -> list[dict]:
    """Run independent Gröbner jobs across worker processes, preserving order.

    Each job: {"polys": [str, ...], "variables": [str, ...], "order": str?}.
    """
    resolved = resolve_workers(workers)
    return process_map(_groebner_job, jobs, workers=resolved)
