"""Local claim checking, with an independent exact coverage construction."""
from decimal import Decimal, localcontext
from math import gcd, isqrt
from .models import RemoteResultEnvelope, VerificationReport
from .protocol import digest
from .registry import OPERATIONS


def check_binding(attempt, candidate):
    if (candidate.attempt_id != attempt.attempt_id or candidate.workspace_id != attempt.workspace_id
            or candidate.execution_digest != attempt.execution_digest
            or candidate.bundle_digest != attempt.bundle_digest
            or candidate.operation != attempt.spec.bundle.request.operation
            or candidate.output_schema != OPERATIONS[candidate.operation]['output_schema']):
        raise ValueError('OUTPUT_BINDING_MISMATCH')


def verify_candidate(attempt, candidate, report_id):
    check_binding(attempt, candidate)
    request = attempt.spec.bundle.request
    fields = dict(report_id=report_id, verifier=OPERATIONS[request.operation]['verifier'],
                  candidate_digest=digest(candidate), bundle_digest=attempt.bundle_digest,
                  execution_digest=attempt.execution_digest, claim=request.required_claim)
    def failed(detail):
        return VerificationReport(**fields, outcome='FAILED', trust='unknown', detail=detail)
    if request.operation == 'cuboid_sweep':
        bound = int(request.parameters.bound)
        if len(candidate.output) > bound * 10:
            return failed('Candidate pair budget exceeded')
        seen = set()
        for pair in candidate.output:
            if not isinstance(pair, tuple) or len(pair) != 2:
                return failed('Invalid pair shape')
            a, b = map(int, pair)
            if not 1 <= a < b <= bound or isqrt(a*a+b*b)**2 != a*a+b*b or (a, b) in seen:
                return failed('Invalid, duplicate or out-of-domain integer witness')
            seen.add((a, b))
        if request.required_claim == 'complete_search':
            # Every primitive positive integer right triangle is generated by
            # coprime m>n of opposite parity; multiples cover nonprimitive pairs.
            # Hypotenuse <= sqrt(2)*bound, so m^2 <= 2*bound is a safe bound.
            expected = set()
            for m in range(2, isqrt(2 * bound) + 1):
                for n in range(1, m):
                    if (m-n) % 2 and gcd(m, n) == 1:
                        a, b = sorted((m*m-n*n, 2*m*n))
                        for scale in range(1, bound // b + 1):
                            expected.add((scale*a, scale*b))
            if seen != expected:
                return failed('Witness set omits or adds members of the independently generated domain')
        detail = ('All positive pairs in 1 <= a < b <= bound, established by integer identities and '
                  'complete Euclid parameterization.' if request.required_claim == 'complete_search'
                  else 'Only the listed integer identities were checked; no search completeness claim.')
        return VerificationReport(**fields, outcome='PASSED', trust='exact', detail=detail)
    if any(not isinstance(v, str) for v in candidate.output):
        return failed('Invalid numerical output shape')
    p = request.parameters
    if len(candidate.output) != len(p.left) + len(p.right) - 1:
        return failed('Convolution output length mismatch')
    with localcontext() as context:
        context.prec = 100
        # Reference is for the fixed binary64 input values, preserving approximate ancestry.
        a = [Decimal.from_float(float(v)) for v in p.left]
        b = [Decimal.from_float(float(v)) for v in p.right]
        expected = [Decimal(0)] * (len(a) + len(b) - 1)
        for i, x in enumerate(a):
            for j, y in enumerate(b):
                expected[i+j] += x*y
        scale = max(Decimal(1), sum(map(abs, a)) * sum(map(abs, b)))
        tolerance = Decimal(128) * Decimal(2)**-52 * scale
        values = [Decimal(v) for v in candidate.output]
        if any(not v.is_finite() for v in values):
            return failed('Nonfinite numerical candidate')
        error = max(abs(x-y) for x, y in zip(expected, values))
        return VerificationReport(**fields, outcome='PASSED' if error <= tolerance else 'FAILED',
            trust='numeric' if error <= tolerance else 'unknown', maximum_error=str(error), tolerance=str(tolerance),
            detail='Infinity-norm error against 100-digit Decimal convolution of binary64 inputs; '
                   'tolerance = 128 * 2^-52 * max(1, ||a||_1 ||b||_1). No forward-error, exact, or interval claim.')


def admit(attempt, candidate, report):
    """Only locally generated evidence reaches MathResult compatibility validators."""
    check_binding(attempt, candidate)
    if (report.outcome != 'PASSED' or report.candidate_digest != digest(candidate)
            or report.bundle_digest != attempt.bundle_digest or report.execution_digest != attempt.execution_digest
            or report.claim != attempt.spec.bundle.request.required_claim):
        raise ValueError('RESULT_NOT_ADMITTED')
    from mathkernel.models import MathResult, TrustLevel, ResultStatus
    from mathkernel_artifacts.evidence import EvidenceBundle, CertificateEvidence, NumericalEvidence
    meta = {'bundle_digest': report.bundle_digest, 'candidate_digest': report.candidate_digest,
            'execution_digest': report.execution_digest, 'verifier_version': report.verifier_version}
    if report.trust == 'exact':
        evidence = EvidenceBundle(certificate=[CertificateEvidence(
            certificate_type='integer-pairs', claim=report.detail, witness=candidate.output,
            verifier=report.verifier, verified=True, trust='exact', support_path='local-independent', metadata=meta)])
        status = ResultStatus.VERIFIED_EXACT
    else:
        evidence = EvidenceBundle(numerical=[NumericalEvidence(precision=53, absolute_error=report.maximum_error,
            residual=report.maximum_error, trust='numeric', support_path='local-numeric',
            metadata={**meta, 'tolerance': report.tolerance, 'claim': report.detail, 'input_ancestry': 'numeric'})])
        status = ResultStatus.VERIFIED_NUMERIC
    return MathResult(ok=True, status='verified', data={'output': candidate.output,
        'checked_claim': report.claim, 'scope': report.detail,
        'execution_provenance': {'target': attempt.spec.target, 'attempt_id': attempt.attempt_id,
                                 'runtime_digest': attempt.spec.runtime.digest, **meta}},
        trust=TrustLevel(report.trust), semantic_status=status, engine=report.verifier,
        claim_evidence={report.claim: evidence}, evidence_bundle=evidence,
        warnings=['Worker metadata is untrusted and did not participate in evidence admission.'])
